# Go CI with Streamline TestContainers
name: Go Integration Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run integration tests
        run: go test -v -tags=integration ./...

      # Example test:
      # func TestWithStreamline(t *testing.T) {
      #     ctx := context.Background()
      #     container, err := streamlinetc.RunForTesting(ctx)
      #     require.NoError(t, err)
      #     defer container.Terminate(ctx)
      #
      #     bootstrap, _ := container.BootstrapServers(ctx)
      #     // Use any Kafka client library unchanged
      # }
